### ISSUE TITLE
Stello AppImage wont run from a Samba share

### ISSUE THREAD

**Issue by toby-1-kenobi** [gracious-tech/stello#16]
I'm really pleased about the feature that lets you put the AppImage and stello_data into one folder and run it from a USB stick on any machine, however, to make it really useful in my situation I need to run that from a folder shared on a local network. I have set up a Samba share from one Ubuntu 22.04 box and mounted it on another. I made sure the folder is editable. When I try to run the AppImage on the second machine I get this error:

> [1355:0210/095913.865719:ERROR:process_singleton_posix.cc(284)] Failed to create /path/to/share/folder/stello_data/SingletonLock: Operation not supported (95)

I suppose this ais a feature request, rather than a bug report, since the docs never mention this as a use case. But it would be a very useful feature for me.

**Comment by toby-1-kenobi** [comment]
If the AppImage could run from the local hard drive, but still access all the data from a share folder, that would be equally useful. Is that possible?

**Comment by shadow-light** [comment]
Hi Toby, thanks for the suggestion. Stello uses Electron, so if that were possible with Chrome then it would be. But I can imagine there being lots of issues with trying to rapidly read and write to a network drive. So this probably won't be possible.

Syncing with another device is a highly requested feature, so it may come one day. But it'll need to be implemented at the application level rather than via the file system.
